#pragma once
#include <QApplication>
#include <QMainWindow>
#include <QTreeView>
#include <QTableView>
#include <QSplitter>
#include <QLineEdit>
#include <QLabel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFileSystemModel>
#include <QSortFilterProxyModel>
#include <QFileIconProvider>
#include <QFileInfo>
#include <QDir>
#include <QDesktopServices>
#include <QUrl>
#include <QDateTime>
#include <QStatusBar>
#include <QHeaderView>
#include <QAction>
#include <QToolBar>
#include <QStyle>